package abap_frontend_semantic_analyze

import "src:ast"
import "src:tokenizer"

Source_File_Role :: enum {
	Full_Source,
	Opened_Dependency,
	Dependency_Interface_Source,
}

Source_File_Provider :: struct {
	source_file_id:                         Source_File_Id,
	role:                                   Source_File_Role,
	uri:                                    string,
	root:                                   ^ast.File,
	root_scope:                             Scope_Id,
	scopes:                                 [dynamic]Scope_Data,
	symbols:                                [dynamic]Symbol_Data,
	decl_infos:                             [dynamic]Decl_Info_Data,
	types:                                  [dynamic]Type_Data,
	structures:                             [dynamic]Structure_Data,
	references:                             [dynamic]Reference_Data,
	message_default_class:                  Message_Class_Use_Data,
	has_message_default_class:              bool,
	message_uses:                           [dynamic]Message_Use_Data,
	message_class_entries:                  [dynamic]Message_Class_Entry_Data,
	diagnostics:                            [dynamic]Diagnostic,
	include_edges:                          [dynamic]Include_Edge,
	table_work_areas:                       [dynamic]Table_Work_Area_Data,
	selection_screen_report_type_positions: [dynamic]tokenizer.Range,
	field_accesses:                         [dynamic]Field_Access,
	table_exprs:                            [dynamic]Table_Expr_Data,
	loop_where_field_contexts:              [dynamic]Loop_Where_Field_Context,
	loop_at_field_contexts:                 [dynamic]Loop_At_Field_Context,
	constructor_for_bindings:               [dynamic]Constructor_For_Binding_Data,
	class_definitions:                      [dynamic]Class_Definition_Data,
	class_inheritance:                      [dynamic]Class_Inheritance_Data,
	class_friends:                          [dynamic]Class_Friend_Data,
	implemented_interfaces:                 [dynamic]Implemented_Interface_Data,
	member_aliases:                         [dynamic]Member_Alias_Data,
	named_arguments:                        [dynamic]Named_Argument_Access,
	call_sites:                             [dynamic]Call_Site_Data,
	call_function_exception_message_sites:  [dynamic]Call_Function_Exception_Message_Site_Data,
	assignment_sites:                       [dynamic]Assignment_Site_Data,
	concatenate_lines_of_sites:             [dynamic]Concatenate_Lines_Of_Site_Data,
	sql_queries:                            [dynamic]Sql_Query_Data,
	sql_sources:                            [dynamic]Sql_Source_Data,
	sql_dynamic_fragments:                  [dynamic]Sql_Dynamic_Fragment_Data,
	sql_projections:                        [dynamic]Sql_Projection_Data,
	sql_name_refs:                          [dynamic]Sql_Name_Ref_Data,
	sql_predicates:                         [dynamic]Sql_Predicate_Data,
	sql_predicate_names:                    [dynamic]Sql_Predicate_Name_Data,
	sql_targets:                            [dynamic]Sql_Target_Data,
	create_data_type_handles:               [dynamic]Create_Data_Type_Handle_Site_Data,
	provided_names:                         [dynamic]string,
	scope_index:                            Scope_Index,
}
