id = "abap"
name = "ABAP"
version = "0.0.1"
schema_version = 1
authors = ["ABAP LSP contributors"]
description = "ABAP syntax support for Zed using the in-repo tree-sitter grammar."
repository = "https://github.com/1Meracle1/abap-lsp"

[grammars.abap]
repository = "file:///D:/dev/rust/abap-lsp"
rev = "74a0c204b9309a6ee20fc94ac0d66c12e3753716"
path = "tree-sitter"
