id = "abap"
name = "ABAP"
version = "0.0.1"
schema_version = 1
authors = ["ABAP LSP contributors"]
description = "ABAP syntax and language server support for Zed."
repository = "https://github.com/1Meracle1/abap-lsp"

[language_servers.abap-language-server]
name = "ABAP Language Server"
languages = ["ABAP"]

[grammars.abap]
repository = "https://github.com/1Meracle1/abap-lsp"
rev = "7ee5c1164c7d754bdd434551a6bae4d4c9749d70"
path = "tree-sitter"
