name = "ABAP"
grammar = "abap"
path_suffixes = ["abap"]
line_comments = ["\" "]
tab_size = 2
hard_tabs = false
word_characters = ["_"]

brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "`", end = "`", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "|", end = "|", close = true, newline = false, not_in = ["string", "comment"] },
]

[overrides.string]
completion_query_characters = ["-", "_", "~", ">", "="]

[overrides.field_symbol]
word_characters = ["_", "<", ">"]
