(comment) @comment
(star_comment) @comment
(line_comment) @comment
(pragma) @preproc
(keyword) @keyword
(number) @number
(string) @string
(string_template) @string.special
(template_text) @string.special
(template_start) @punctuation.bracket
(template_end) @punctuation.bracket
(template_interpolation_start) @punctuation.bracket
(template_interpolation_end) @punctuation.bracket
(field_symbol) @variable.special
(namespaced_identifier) @variable.special
(cte_identifier) @variable.special
(identifier) @variable
(escaped_identifier) @variable
(operator) @operator
(punctuation) @punctuation.delimiter
