use std::collections::HashSet;
use std::sync::Arc;

use crate::{CompletionInsertion, KeywordCompletionItem};

const ABAP_KEYWORD_COMPLETIONS: &[&str] = &[
    "ABSTRACT",
    "ACCEPTING",
    "ADD",
    "ADJACENT",
    "ALIASES",
    "ALL",
    "ALPHA",
    "AND",
    "APPEND",
    "APPENDING",
    "AS",
    "ASCENDING",
    "ASSERT",
    "ASSIGN",
    "ASSIGNED",
    "ASSIGNING",
    "AT",
    "AUTHORITY",
    "BACK",
    "BACKGROUND",
    "BADI",
    "BASE",
    "BEGIN",
    "BETWEEN",
    "BINARY",
    "BIT",
    "BLANKS",
    "BLOCK",
    "BOUND",
    "BREAK",
    "BY",
    "BYTE",
    "CALL",
    "CASE",
    "CAST",
    "CASTING",
    "CATCH",
    "CHANGING",
    "CHARACTER",
    "CHECK",
    "CHECKBOX",
    "CIRCULAR",
    "CLASS",
    "CLEAR",
    "CLOSE",
    "CN",
    "CO",
    "COLLECT",
    "COMMAND",
    "COMMENT",
    "COMMIT",
    "COMMUNICATION",
    "COMPARING",
    "COMPONENT",
    "COMPONENTS",
    "COMPUTE",
    "CONCATENATE",
    "COND",
    "CONDENSE",
    "CONSTANTS",
    "CONTEXTS",
    "CONTINUE",
    "CONTROL",
    "CONTROLS",
    "CONV",
    "CONVERT",
    "CORRESPONDING",
    "CP",
    "CREATE",
    "CS",
    "CURSOR",
    "DATA",
    "DATASET",
    "DATE",
    "DECIMALS",
    "DEFAULT",
    "DEFERRED",
    "DEFINE",
    "DEFINITION",
    "DELETE",
    "DELETING",
    "DEMAND",
    "DESCENDING",
    "DESCRIBE",
    "DESTINATION",
    "DETAIL",
    "DISPLAY",
    "DISTANCE",
    "DISTINCT",
    "DIVIDE",
    "DO",
    "DUPLICATE",
    "DUPLICATES",
    "DURATION",
    "EDITOR",
    "ELSE",
    "ELSEIF",
    "EMPTY",
    "END",
    "ENDAT",
    "ENDCASE",
    "ENDCLASS",
    "ENDDO",
    "ENDFORM",
    "ENDFUNCTION",
    "ENDIF",
    "ENDINTERFACE",
    "ENDLOOP",
    "ENDMETHOD",
    "ENDMODULE",
    "ENDSELECT",
    "ENDTRY",
    "ENDWHILE",
    "ENHANCEMENT",
    "ENTRIES",
    "EQ",
    "EVENT",
    "EVENTS",
    "EXCEPT",
    "EXCEPTION",
    "EXCEPTIONS",
    "EXEC",
    "EXIT",
    "EXPORTING",
    "EXTENSION",
    "EXTRACT",
    "FETCH",
    "FIELD",
    "FIELDS",
    "FILTER",
    "FILTERS",
    "FINAL",
    "FIND",
    "FIRST",
    "FOR",
    "FORM",
    "FORMAT",
    "FOUND",
    "FRAME",
    "FREE",
    "FRIENDS",
    "FROM",
    "FUNCTION",
    "GAPS",
    "GE",
    "GET",
    "GLOBAL",
    "GROUP",
    "GROUPING",
    "GROUPS",
    "GT",
    "HANDLE",
    "HANDLER",
    "HARMLESS",
    "HASHED",
    "HEADER",
    "HEADING",
    "HIDE",
    "HOLD",
    "ID",
    "IF",
    "IGNORING",
    "IMPLEMENTATION",
    "IMPORT",
    "IMPORTING",
    "IN",
    "INCLUDE",
    "INDEX",
    "INFOTYPES",
    "INHERITING",
    "INIT",
    "INITIAL",
    "INITIALIZATION",
    "INJECTION",
    "INNER",
    "INPUT",
    "INSERT",
    "INSTANCE",
    "INTERFACE",
    "INTERFACES",
    "INTERVALS",
    "INTO",
    "IS",
    "JOB",
    "JOIN",
    "JUSTIFIED",
    "KEEPING",
    "KEY",
    "KEYS",
    "LE",
    "LEADING",
    "LEAVE",
    "LEFT",
    "LENGTH",
    "LET",
    "LEVEL",
    "LIKE",
    "LINE",
    "LINES",
    "LIST",
    "LISTBOX",
    "LOAD",
    "LOCAL",
    "LOG",
    "LOOP",
    "LOWER",
    "LT",
    "MAPPING",
    "MATCH",
    "MATCHCODE",
    "MAXIMUM",
    "MEMORY",
    "MESSAGE",
    "METHOD",
    "METHODS",
    "MINIMUM",
    "MODE",
    "MODIFY",
    "MODULE",
    "MOVE",
    "MULTIPLY",
    "NE",
    "NEW",
    "NEXT",
    "NO",
    "NODES",
    "NON",
    "NOT",
    "NULL",
    "NUMBER",
    "OBJECT",
    "OBLIGATORY",
    "OCCURENCES",
    "OCCURRENCE",
    "OCCURRENCES",
    "OF",
    "OFFSET",
    "OLE",
    "ON",
    "OPEN",
    "OPTIONAL",
    "OPTIONS",
    "OR",
    "ORDER",
    "OTHERS",
    "OUT",
    "OUTER",
    "OUTPUT",
    "OVERLAY",
    "PACK",
    "PACKAGE",
    "PAGE",
    "PARAMETER",
    "PARAMETERS",
    "PERFORM",
    "PF",
    "PLACES",
    "POINT",
    "POOL",
    "POOLS",
    "POSITION",
    "PRIMARY",
    "PRINT",
    "PRIVATE",
    "PROCEDURE",
    "PROCESSING",
    "PROGRAM",
    "PROTECTED",
    "PROVIDE",
    "PUBLIC",
    "PUSHBUTTON",
    "PUT",
    "RADIOBUTTON",
    "RAISE",
    "RAISING",
    "RANGE",
    "RANGES",
    "READ",
    "RECEIVE",
    "RECEIVING",
    "REDEFINITION",
    "REDUCE",
    "REF",
    "REFERENCE",
    "REFRESH",
    "REGEX",
    "REJECT",
    "REPLACE",
    "REPORT",
    "REQUESTED",
    "RESERVE",
    "RESPECTING",
    "RESULT",
    "RESULTS",
    "RESUMABLE",
    "RESUME",
    "RETRY",
    "RETURN",
    "RETURNING",
    "RISK",
    "ROLLBACK",
    "ROWS",
    "SCREEN",
    "SCROLL",
    "SEAM",
    "SEARCH",
    "SECONDS",
    "SECTION",
    "SELECT",
    "SELECTION",
    "SEPARATED",
    "SET",
    "SHIFT",
    "SHORT",
    "SIGN",
    "SINGLE",
    "SIZE",
    "SKIP",
    "SORT",
    "SORTED",
    "SOURCE",
    "SPLIT",
    "SQL",
    "STABLE",
    "STAMP",
    "STANDARD",
    "START",
    "STARTING",
    "STATICS",
    "STATUS",
    "STOP",
    "STRUCTURE",
    "SUBMATCHES",
    "SUBMIT",
    "SUBSCREEN",
    "SUBTRACT",
    "SUM",
    "SUMMARY",
    "SUMMING",
    "SUPPLIED",
    "SUPPLY",
    "SUPPRESS",
    "SWITCH",
    "SYMBOL",
    "SYMBOLS",
    "SYNTAX",
    "SYSTEM",
    "TABLE",
    "TABLES",
    "TABSTRIP",
    "TARGET",
    "TASK",
    "TEST",
    "TESTING",
    "TEXT",
    "TEXTPOOL",
    "THEN",
    "TIME",
    "TIMES",
    "TITLE",
    "TITLEBAR",
    "TO",
    "TRAILING",
    "TRANSACTION",
    "TRANSFER",
    "TRANSFORMATION",
    "TRANSLATE",
    "TRANSPORTING",
    "TRUNCATE",
    "TRY",
    "TYPE",
    "TYPES",
    "ULINE",
    "UNASSIGN",
    "UNIQUE",
    "UNPACK",
    "UNTIL",
    "UP",
    "UPDATE",
    "UPPER",
    "USER",
    "USING",
    "VALUE",
    "VALUES",
    "VIA",
    "VISIBLE",
    "WAIT",
    "WHEN",
    "WHERE",
    "WHILE",
    "WINDOW",
    "WITH",
    "WORK",
    "WRITE",
    "XML",
    "ZONE",
    "APPEND INITIAL LINE",
    "APPEND LINES OF",
    "AT END OF",
    "AT FIRST",
    "AT LAST",
    "AT LINE-SELECTION",
    "AT NEW",
    "AT SELECTION-SCREEN",
    "AUTHORITY-CHECK",
    "CALL BADI",
    "CALL FUNCTION",
    "CALL METHOD",
    "CALL SCREEN",
    "CALL SELECTION-SCREEN",
    "CALL TRANSACTION",
    "CALL TRANSFORMATION",
    "CLASS DATA",
    "CLASS-DATA",
    "CLASS DEFINITION",
    "CLASS IMPLEMENTATION",
    "CLASS-METHODS",
    "CLASS-EVENTS",
    "CLASS-POOL",
    "CLOSE CURSOR",
    "COMMIT WORK",
    "CONCATENATE INTO",
    "CONDENSE NO-GAPS",
    "CONSTANTS BEGIN OF",
    "CONSTANTS END OF",
    "CONVERT DATE",
    "CONVERT TIME STAMP",
    "CREATE DATA",
    "CREATE OBJECT",
    "DATA BEGIN OF",
    "DATA END OF",
    "DAYLIGHT SAVING TIME",
    "DELETE ADJACENT DUPLICATES",
    "DELETE FROM",
    "DELETE TABLE",
    "END OF PAGE",
    "END OF SELECTION",
    "END-OF-PAGE",
    "END-OF-SELECTION",
    "FIELD-SYMBOLS",
    "FIND ALL OCCURRENCES OF",
    "FIND FIRST OCCURRENCE OF",
    "FOR ALL ENTRIES",
    "FOR UPDATE",
    "FUNCTION-POOL",
    "GET BIT",
    "GET REFERENCE OF",
    "GET TIME",
    "GET TIME STAMP FIELD",
    "GROUP BY",
    "IF FOUND",
    "IN PROGRAM",
    "IN UPDATE TASK",
    "INCLUDE STRUCTURE",
    "INCLUDE TYPE",
    "INTERFACE LOAD",
    "INTERFACE-POOL",
    "LIKE LINE OF",
    "LIKE TABLE OF",
    "LINE COUNT",
    "LINE SIZE",
    "LOOP AT",
    "MESSAGE ID",
    "MODIFY SCREEN",
    "MODIFY TABLE",
    "MOVE-CORRESPONDING",
    "NEW LINE",
    "NEW PAGE",
    "NO FIELDS",
    "NO-GAPS",
    "OPEN CURSOR",
    "ORDER BY",
    "PACKAGE SIZE",
    "PARAMETERS DEFAULT",
    "PARAMETERS LOWER CASE",
    "PRIVATE SECTION",
    "PROTECTED SECTION",
    "PUBLIC SECTION",
    "RAISE EXCEPTION",
    "RAISE EVENT",
    "READ TABLE",
    "REPLACE ALL OCCURRENCES OF",
    "REPLACE FIRST OCCURRENCE OF",
    "ROLLBACK WORK",
    "SELECT DISTINCT",
    "SELECT FIELDS",
    "SELECT FROM",
    "SELECT SINGLE",
    "SELECT-OPTIONS",
    "SELECTION-SCREEN",
    "SELECTION-SCREEN BEGIN OF BLOCK",
    "SELECTION-SCREEN END OF BLOCK",
    "SET BIT",
    "SET HANDLER",
    "SET PARAMETER ID",
    "SET PF-STATUS",
    "SET TITLEBAR",
    "SORT BY",
    "SPLIT AT",
    "SPLIT INTO TABLE",
    "START OF SELECTION",
    "START-OF-SELECTION",
    "SUBMIT VIA JOB",
    "TOP OF PAGE",
    "TOP-OF-PAGE",
    "TRANSFER TO",
    "TRANSPORTING NO FIELDS",
    "TYPE HASHED TABLE OF",
    "TYPE POOL",
    "TYPE-POOL",
    "TYPE-POOLS",
    "TYPE RANGE OF",
    "TYPE REF TO",
    "TYPE SORTED TABLE OF",
    "TYPE STANDARD TABLE OF",
    "TYPES BEGIN OF",
    "TYPES END OF",
    "UPDATE TASK LOCAL",
    "USING KEY",
    "VALUE TYPE",
    "WITH DEFAULT KEY",
    "WITH EMPTY KEY",
    "WITH FREE SELECTIONS",
    "WITH HEADER LINE",
    "WITH HOLD",
    "WITH KEY",
    "WITH NON-UNIQUE KEY",
    "WITH UNIQUE KEY",
    "WRITE TO",
];

pub(crate) fn keyword_completion_items(prefix: &str) -> Vec<KeywordCompletionItem> {
    if prefix.is_empty() {
        return Vec::new();
    }

    let mut seen = HashSet::<&str>::new();
    let mut items: Vec<_> = ABAP_KEYWORD_COMPLETIONS
        .iter()
        .copied()
        .filter(|label| starts_with_ignore_ascii_case(label, prefix))
        .filter(|label| seen.insert(*label))
        .map(|label| KeywordCompletionItem {
            name: Arc::from(label),
            insertion: CompletionInsertion {
                plain_text: label.to_string(),
                snippet_text: None,
            },
        })
        .collect();
    items.sort_by(|left, right| left.name.cmp(&right.name));
    items
}

fn starts_with_ignore_ascii_case(text: &str, prefix: &str) -> bool {
    text.get(..prefix.len())
        .is_some_and(|head| head.eq_ignore_ascii_case(prefix))
}
