[package]
name = "abap_lsp"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
abap_cache = { path = "../abap_cache" }
abap_dependency_store = { path = "../abap_dependency_store" }
abap_jsonrpc = { path = "../abap_jsonrpc" }
abap_lexer = { path = "../abap_lexer" }
abap_parser = { path = "../abap_parser" }
abap_runtime = { path = "../abap_runtime" }
abap_symbols = { path = "../abap_symbols" }
lsp-types.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
